
---
- hosts: main_node_backup
  gather_facts: False
  become: true
  tasks:
      - name: Run mongodb_exec.py
        shell: |
          python3 /opt/custom/db_backup/mongodb_exec.py | tail -n 1
        register: result

      - name: Check result
        debug:
          msg: "OK"
        when: result.stdout == "1"

      - name: Check result
        debug:
          msg: "FAILED"
        when: result.stdout == "0"

      - name: Run tg_bot.py
        shell: |
            python3 /opt/ansible/db_backup/tg_bot.py --db_type MongoDB
        when: result.stdout == "1"
        delegate_to: localhost




